version: "2"
services:
  base:
    container_name: genova-base
    build: .
    env_file: .env
    volumes:
      - .:/data/rails
      - /var/run/docker.sock:/var/run/docker.sock
  rails:
    container_name: genova-rails
    extends:
      service: base
    build: ./etc/docker/rails
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - redis
  sidekiq:
    container_name: genova-sidekiq
    extends:
      service: base
    build: ./etc/docker/sidekiq
    depends_on:
      - mongo
      - redis
  cron:
    container_name: genova-cron
    extends:
      service: base
    build: ./etc/docker/cron
  mongo:
    container_name: genova-mongo
    image: mongo:3.4.9
    ports:
      - 27017:27017
  redis:
    container_name: genova-redis
    image: redis:3.2
    ports:
      - 6379:6379
  # slack:
  #   container_name: genova-slack
  #   build: ./etc/docker/slack
  #   env_file: .env
  #   ports:
  #     - 9292:9292
  #   depends_on:
  #     - mongo
